//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBooking
    {
        public int BookingId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CitizenshipPhoto { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public Nullable<int> AmountPaid { get; set; }
        public string BookingStatus { get; set; }
    
        public virtual tblItem tblItem { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
