//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTestimony
    {
        public int TestimonyId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Location { get; set; }
        public string TestimonyDescription { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
